version: '3.9'


services:
  auth-fyp:
    container_name: auth-fyp
    image: auth-fyp:latest
    build:
      context: fyp-be/Auth
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"

  pharmacy-fyp:
    container_name: pharmacy-fyp
    image: pharmacy-fyp:latest
    build:
      context: fyp-be
      dockerfile: ./pharmacy.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-fyp

  appointment-fyp:
    container_name: appointment-fyp
    image: appointment-fyp:latest
    build:
      context: fyp-be
      dockerfile: ./appointment.dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres-fyp

  postgres-fyp:
    container_name: postgres-fyp
    image: postgres:15.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ahmadobeid
      POSTGRES_PASSWORD: ahmadobeidpass
      POSTGRES_DB: fyp

  notification-scheduler-fyp:
    container_name: notification-scheduler-fyp
    image: notification-scheduler-fyp:latest
    build:
      context: fyp-be/notif-scheduler
      dockerfile: ./notif-scheduler.dockerfile
    depends_on:
      - postgres-fyp

  minio:
    image: minio/minio:RELEASE.2022-10-08T20-11-00Z.fips
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopass
    command: server --console-address ":9001" /data

  nginx:
    container_name: nginx-fyp
    image: nginx-fyp:latest
    build:
      context: fyp-be/nginx
      dockerfile: dockerfile
    ports:
      - "5000:80"

  fyp-fe:
    container_name: fyp-fe
    image: fyp-fe:latest
    build:
      context: ./fyp-fe
      dockerfile: Dockerfile
      args:
        http_proxy: ''
        https_proxy: ''
    ports:
      - "4200:80"