version: '3.9'


services:
  module-controller-fyp:
    container_name: module-controller-fyp
    image: module-controller-fyp:latest
    build:
      context: fyp-be/ModuleController
      dockerfile: ./Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fyp-network

  auth-fyp:
    container_name: auth-fyp
    image: auth-fyp:latest
    build:
      context: fyp-be/Auth
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    networks:
      - fyp-network

  user-fyp:
    container_name: user-fyp
    image: user-fyp:latest
    build:
      context: fyp-be
      dockerfile: ./user.dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - postgres-fyp
    networks:
      - fyp-network

  pharmacy-fyp:
    container_name: pharmacy-fyp
    image: pharmacy-fyp:latest
    build:
      context: fyp-be
      dockerfile: ./pharmacy.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-fyp
    networks:
      - fyp-network

  appointment-fyp:
    container_name: appointment-fyp
    image: appointment-fyp:latest
    build:
      context: fyp-be
      dockerfile: ./appointment.dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres-fyp
    networks:
      - fyp-network

  postgres-fyp:
    container_name: postgres-fyp
    image: postgres:15.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ahmadobeid
      POSTGRES_PASSWORD: ahmadobeidpass
      POSTGRES_DB: fyp
    networks:
      - fyp-network

  notification-scheduler-fyp:
    container_name: notification-scheduler-fyp
    image: notification-scheduler-fyp:latest
    build:
      context: fyp-be/notif-scheduler
      dockerfile: ./notif-scheduler.dockerfile
    depends_on:
      - postgres-fyp
    networks:
      - fyp-network

  nginx:
    container_name: nginx-fyp
    image: nginx-fyp:latest
    build:
      context: fyp-be/nginx
      dockerfile: dockerfile
    ports:
      - "5000:80"
    networks:
      - fyp-network

  fyp-fe:
    container_name: fyp-fe
    image: fyp-fe:latest
    build:
      context: ./fyp-fe
      dockerfile: Dockerfile
      args:
        http_proxy: ''
        https_proxy: ''
    ports:
      - "4200:80"
    networks:
      - fyp-network

networks:
  fyp-network:
    driver: bridge