version: '3.9'


services:
  pharmacy-fyp:
    container_name: pharmacy-fyp
    image: pharmacy-fyp:latest
    build:
      context: fyp-be
      dockerfile: ./pharmacy.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-fyp

  appointment-fyp:
    container_name: appointment-fyp
    image: appointment-fyp:latest
    build:
      context: fyp-be
      dockerfile: ./appointment.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-fyp

  postgres-fyp:
    container_name: postgres-fyp
    image: postgres:15.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ahmadobeid
      POSTGRES_PASSWORD: ahmadobeidpass
      POSTGRES_DB: fyp

  fyp-fe:
    image: fyp-fe:latest
    build:
      context: ./fyp-fe
      dockerfile: Dockerfile
      args:
        http_proxy: ''
        https_proxy: ''
    ports:
      - "4200:80"